name: PacificOcean
options:
  xcodeVersion: '15.0'
  minimumXcodeGenVersion: '2.25.0'
  deploymentTarget:
    iOS: "16.0"
  groupSortPosition: top
  developmentLanguage: ru

settings:
  base:
    APP_VERSION: 1.0.0
    BUNDLE_VERSION: 1
    ENABLE_BITCODE: no
    DISPLAY_NAME: "pcfcocean"

appFonts: &app_Fonts [
  CustomFont.ttf
]

targets:
  PacificOcaen:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: ./PacificOcean
      - path: ./DesignSystem
      - path: ./Swift
    info:
      path: ./PacificOcean/info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.pcfcocean
